<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use VCR\VCR;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        VCR::turnOn();
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        VCR::turnOff();
    }
}
